const seedProperties=[
{id:1,name:'Maple Residence',address:'12 Maple Ave, Austin',rent:1250,status:'Paid',tenant:'Ahmed Hassan',image:'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80',leaseEnd:'2027-01-31'},
{id:2,name:'Oak Loft',address:'48 Oak Street, Austin',rent:1200,status:'Due soon',tenant:'Sarah Ali',image:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',leaseEnd:'2026-10-15'},
{id:3,name:'Brick House',address:'93 Pine Road, Dallas',rent:1200,status:'Overdue',tenant:'Omar Khaled',image:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',leaseEnd:'2026-12-01'},
{id:4,name:'Sunset Apartment',address:'7 Sunset Blvd, Dallas',rent:1150,status:'Vacant',image:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80'},
{id:5,name:'Cedar Studio',address:'22 Cedar Lane, Austin',rent:980,status:'Paid',tenant:'Laila Mostafa',image:'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',leaseEnd:'2027-03-20'},
{id:6,name:'North View',address:'81 North Ave, Houston',rent:1320,status:'Paid',tenant:'Mina Adel',image:'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',leaseEnd:'2027-05-10'}];
const seedTenants=[
{id:1,name:'Ahmed Hassan',propertyId:1,email:'ahmed@example.com',phone:'+1 555 1200',leaseStart:'2026-02-01',leaseEnd:'2027-01-31',rent:1250,status:'Paid'},
{id:2,name:'Sarah Ali',propertyId:2,email:'sarah@example.com',phone:'+1 555 2200',leaseStart:'2025-10-15',leaseEnd:'2026-10-15',rent:1200,status:'Due soon'},
{id:3,name:'Omar Khaled',propertyId:3,email:'omar@example.com',phone:'+1 555 3200',leaseStart:'2025-12-01',leaseEnd:'2026-12-01',rent:1200,status:'Overdue'},
{id:4,name:'Laila Mostafa',propertyId:5,email:'laila@example.com',phone:'+1 555 5200',leaseStart:'2026-03-20',leaseEnd:'2027-03-20',rent:980,status:'Paid'},
{id:5,name:'Mina Adel',propertyId:6,email:'mina@example.com',phone:'+1 555 6200',leaseStart:'2026-05-10',leaseEnd:'2027-05-10',rent:1320,status:'Paid'}];
const seedExpenses=[{id:1,propertyId:1,category:'Maintenance',amount:240,date:'2026-08-04',note:'AC service'},{id:2,propertyId:2,category:'Repairs',amount:180,date:'2026-08-09',note:'Door lock'},{id:3,propertyId:3,category:'Utilities',amount:120,date:'2026-08-12',note:'Common utilities'},{id:4,propertyId:5,category:'Cleaning',amount:80,date:'2026-08-18',note:'Turnover clean'}];
const seedAlerts=[{id:1,title:'Rent overdue',detail:'Brick House is 7 days overdue · $1,200',severity:'high',resolved:false},{id:2,title:'Lease ending soon',detail:'Oak Loft lease ends in 48 days',severity:'medium',resolved:false},{id:3,title:'Vacant unit',detail:'Sunset Apartment currently has no tenant',severity:'low',resolved:false}];
function load(key,seed){try{return JSON.parse(localStorage.getItem(key))||seed}catch{return seed}}function save(key,val){localStorage.setItem(key,JSON.stringify(val))}let properties=load('los-properties',seedProperties),tenants=load('los-tenants',seedTenants),expenses=load('los-expenses',seedExpenses),alerts=load('los-alerts',seedAlerts),page='home';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);const cls=s=>s.toLowerCase().replace(' ','-');const status=s=>`<span class="status ${cls(s)}">${s}</span>`;const navItems=[['home','Home'],['properties','Properties'],['tenants','Tenants'],['rent','Rent tracker'],['expenses','Expenses'],['alerts','Alerts']];
function renderNav(){document.getElementById('nav').innerHTML=navItems.map(([id,label])=>`<button data-page="${id}" class="${page===id?'active':''}"><span>${label}</span>${id==='alerts'&&alerts.filter(a=>!a.resolved).length?`<em>${alerts.filter(a=>!a.resolved).length}</em>`:''}</button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.getElementById('portfolioCount').textContent=`${properties.length} properties`}
function propertyCard(p){return `<button class="property-card" data-property="${p.id}"><div class="image-wrap"><img src="${p.image}" alt="${p.name}">${status(p.status)}</div><div class="property-copy"><div><strong>${p.name}</strong><span>${p.address}</span></div><div class="property-foot"><span>${p.tenant||'No tenant yet'}</span><strong>${money(p.rent)}/mo</strong></div></div></button>`}
function sectionTitle(title,sub){return `<div class="section-title"><div><h2>${title}</h2><p>${sub}</p></div></div>`}
function home(){let expected=properties.filter(p=>p.status!=='Vacant').reduce((a,p)=>a+p.rent,0),collected=properties.filter(p=>p.status==='Paid').reduce((a,p)=>a+p.rent,0),overdue=properties.filter(p=>p.status==='Overdue').reduce((a,p)=>a+p.rent,0),occ=Math.round(properties.filter(p=>p.status!=='Vacant').length/properties.length*100),first=alerts.find(a=>!a.resolved);return `<section class="summary-row"><div><span>Expected rent</span><strong>${money(expected)}</strong></div><div><span>Collected</span><strong>${money(collected)}</strong></div><div><span>Overdue</span><strong class="danger-text">${money(overdue)}</strong></div><div class="occupancy"><span>Occupancy</span><strong>${occ}%</strong><small>${properties.filter(p=>p.status!=='Vacant').length} of ${properties.length} units</small></div></section><section class="attention"><div><div><strong>Needs attention</strong><span>${first?first.detail:'Everything looks good'}</span></div></div><button onclick="page='alerts';render()">Review alerts</button></section>${sectionTitle('Your properties','Your portfolio at a glance')}<div class="property-grid">${properties.map(propertyCard).join('')}</div>`}
function propertiesView(){return `${sectionTitle('Properties','See every unit without spreadsheet noise')}<div class="property-grid">${properties.map(propertyCard).join('')}</div>`}
function tenantsView(){return `<div class="toolbar"><div class="search"><input id="tenantSearch" placeholder="Search tenants or properties"></div></div><div class="tenant-list" id="tenantList">${tenantRows('')}</div>`}function tenantRows(q){q=q.toLowerCase();return tenants.filter(t=>t.name.toLowerCase().includes(q)||(properties.find(p=>p.id===t.propertyId)?.name||'').toLowerCase().includes(q)).map(t=>{let p=properties.find(x=>x.id===t.propertyId);let initials=t.name.split(' ').map(x=>x[0]).slice(0,2).join('');return `<div class="tenant-row"><div class="avatar">${initials}</div><div class="tenant-main"><strong>${t.name}</strong><span>${p?.name||''}</span></div><div><small>Rent</small><strong>${money(t.rent)}</strong></div><div><small>Lease ends</small><strong>${new Date(t.leaseEnd).toLocaleDateString()}</strong></div>${status(t.status)}</div>`}).join('')}
function rentView(){return `${sectionTitle('August rent','Who paid, who is due, who is late')}<div class="rent-list">${properties.filter(p=>p.status!=='Vacant').map(p=>`<div class="rent-row"><div><span class="rent-date">01</span></div><div class="rent-main"><strong>${p.tenant}</strong><span>${p.name}</span></div><strong>${money(p.rent)}</strong>${status(p.status)}${p.status!=='Paid'?`<button class="secondary" data-paid="${p.id}">✓ Mark paid</button>`:`<span class="paid-note">Received</span>`}</div>`).join('')}</div>`}
function expensesView(){return `<div class="split-head">${sectionTitle('Expenses','Simple property costs, one clean view')}<button class="primary" id="addExpenseBtn">＋ Add expense</button></div><div class="expense-total"><span>This month</span><strong>${money(expenses.reduce((a,e)=>a+e.amount,0))}</strong></div><div class="expense-list">${expenses.map(e=>{let p=properties.find(x=>x.id===e.propertyId);return `<div class="expense-row"><div class="expense-icon">$</div><div><strong>${e.category}</strong><span>${p?.name||''} · ${e.note||''}</span></div><span>${new Date(e.date).toLocaleDateString()}</span><strong>${money(e.amount)}</strong></div>`}).join('')}</div>`}
function alertsView(){let active=alerts.filter(a=>!a.resolved);return `${sectionTitle('Alerts','Only the things that genuinely need your attention')}<div class="alert-list">${active.length?active.map(a=>`<div class="alert-row ${a.severity}"><div class="alert-dot"></div><div><strong>${a.title}</strong><span>${a.detail}</span></div><button class="secondary" data-resolve="${a.id}">Resolve</button></div>`).join(''):`<div class="empty-state"><strong>All clear</strong><span>No active alerts right now.</span></div>`}</div>`}
function render(){renderNav();document.getElementById('pageTitle').textContent=page==='home'?'Good morning, Alex':navItems.find(n=>n[0]===page)?.[1];let html=page==='home'?home():page==='properties'?propertiesView():page==='tenants'?tenantsView():page==='rent'?rentView():page==='expenses'?expensesView():alertsView();document.getElementById('content').innerHTML=html;bind()}
function bind(){document.querySelectorAll('[data-property]').forEach(el=>el.onclick=()=>openProperty(Number(el.dataset.property)));document.querySelectorAll('[data-paid]').forEach(el=>el.onclick=()=>{let id=Number(el.dataset.paid);properties=properties.map(p=>p.id===id?{...p,status:'Paid'}:p);tenants=tenants.map(t=>t.propertyId===id?{...t,status:'Paid'}:t);save('los-properties',properties);save('los-tenants',tenants);render()});document.querySelectorAll('[data-resolve]').forEach(el=>el.onclick=()=>{let id=Number(el.dataset.resolve);alerts=alerts.map(a=>a.id===id?{...a,resolved:true}:a);save('los-alerts',alerts);render()});let s=document.getElementById('tenantSearch');if(s)s.oninput=e=>document.getElementById('tenantList').innerHTML=tenantRows(e.target.value);let ae=document.getElementById('addExpenseBtn');if(ae)ae.onclick=openExpense}
function modal(title,body){document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h3>${title}</h3><button id="closeModal">×</button></div>${body}</div></div>`;document.getElementById('closeModal').onclick=closeModal;document.querySelector('.modal-backdrop').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()}}
function closeModal(){document.getElementById('modalRoot').innerHTML=''}function openProperty(id){let p=properties.find(x=>x.id===id);modal(p.name,`<div class="property-detail"><img src="${p.image}" alt=""><div class="detail-grid"><div><span>Address</span><strong>${p.address}</strong></div><div><span>Monthly rent</span><strong>${money(p.rent)}</strong></div><div><span>Tenant</span><strong>${p.tenant||'Vacant'}</strong></div><div><span>Status</span>${status(p.status)}</div></div></div>`)}
function openAddProperty(){modal('Add property',`<form class="form" id="propertyForm"><label>Name<input name="name" required placeholder="e.g. River House"></label><label>Address<input name="address" required placeholder="Street, city"></label><label>Monthly rent<input name="rent" required type="number" min="0"></label><button class="primary" type="submit">Add property</button></form>`);document.getElementById('propertyForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);properties.push({id:Date.now(),name:f.get('name'),address:f.get('address'),rent:Number(f.get('rent')),status:'Vacant',image:'https://images.unsplash.com/photo-1600585152915-d208bec867a1?auto=format&fit=crop&w=1200&q=80'});save('los-properties',properties);closeModal();render()}}
function openExpense(){modal('Add expense',`<form class="form" id="expenseForm"><label>Property<select name="propertyId">${properties.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select></label><label>Category<input name="category" required placeholder="Maintenance"></label><label>Amount<input name="amount" required type="number" min="0"></label><label>Date<input name="date" required type="date"></label><label>Note<input name="note" placeholder="Optional note"></label><button class="primary" type="submit">Save expense</button></form>`);document.getElementById('expenseForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);expenses.push({id:Date.now(),propertyId:Number(f.get('propertyId')),category:f.get('category'),amount:Number(f.get('amount')),date:f.get('date'),note:f.get('note')});save('los-expenses',expenses);closeModal();render()}}
document.getElementById('addPropertyBtn').onclick=openAddProperty;render();