(()=>{
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
let mounted=false,overlay=null;
function isAdmin(){return !!window.__LANDLORD_LICENSE__?.admin}
function mount(){if(mounted||!isAdmin())return;mounted=true;const add=()=>{if(!isAdmin())return;const side=q('.side-bottom');if(side&&!q('#licenseAdminBtn')){const b=document.createElement('button');b.id='licenseAdminBtn';b.className='btn ghost small license-admin-btn';b.textContent='License manager';b.onclick=openManager;side.appendChild(b)}const more=q('.more-actions');if(more&&!q('#mobileLicenseAdmin')){const b=document.createElement('button');b.id='mobileLicenseAdmin';b.textContent='License manager';b.onclick=()=>{q('.mobile-sheet-wrap')?.remove();openManager()};more.prepend(b)}};add();new MutationObserver(()=>requestAnimationFrame(add)).observe(document.documentElement,{childList:true,subtree:true})}
async function fetchLicenses(){const sb=window.__LANDLORD_SUPABASE__;const {data,error}=await sb.rpc('admin_list_licenses');if(error)throw error;return data||[]}
function fmtDate(v){if(!v)return'—';try{return new Date(v).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}catch{return'—'}}
function renderRows(rows){const list=q('#licenseList',overlay),stats=q('#licenseStats',overlay);const unused=rows.filter(x=>x.status==='unused').length,active=rows.filter(x=>x.status==='active').length,revoked=rows.filter(x=>x.status==='revoked').length;stats.innerHTML=`<div class="license-stat"><span>Unused</span><strong>${unused}</strong></div><div class="license-stat"><span>Activated</span><strong>${active}</strong></div><div class="license-stat"><span>Revoked</span><strong>${revoked}</strong></div>`;if(!rows.length){list.innerHTML='<div class="license-empty">No activation codes yet.</div>';return}list.innerHTML=rows.map(x=>`<div class="license-row" data-license="${x.id}"><div class="license-code"><strong>•••• ${x.code_suffix}</strong><small>${x.plan}</small></div><div class="license-email"><strong>${x.activated_email||'Not activated'}</strong><small>${x.activated_at?`Activated ${fmtDate(x.activated_at)}`:`Created ${fmtDate(x.created_at)}`}</small></div><span class="license-status ${x.status}">${x.status}</span><div class="license-meta"><small>${x.source||'manual'}</small></div>${x.status==='active'?'<button class="license-revoke">Revoke</button>':'<span></span>'}</div>`).join('');qa('.license-revoke',list).forEach(b=>b.onclick=async()=>{const row=b.closest('[data-license]');if(!confirm('Revoke this license? The customer will lose access on their next license check.'))return;b.disabled=true;const {error}=await window.__LANDLORD_SUPABASE__.rpc('admin_revoke_license',{p_license_id:row.dataset.license});if(error){showError(error.message);b.disabled=false;return}await refresh()})}
function showError(t=''){const e=q('#licenseError',overlay);if(e)e.textContent=t}
async function refresh(){try{showError('');renderRows(await fetchLicenses())}catch(e){console.error(e);showError('Could not load licenses.')}}
async function openManager(){if(!isAdmin())return;if(overlay)overlay.remove();overlay=document.createElement('div');overlay.className='license-admin-overlay';overlay.innerHTML=`<div class="license-admin-shell"><div class="license-admin-head"><div><small>Landlord OS Admin</small><h2>License manager</h2></div><button id="licenseClose">×</button></div><div class="license-generator"><input id="licenseCount" type="number" min="1" max="100" value="10" aria-label="Number of codes"><input id="licenseSource" value="Etsy" placeholder="Source e.g. Etsy"><button id="generateLicenses">Generate codes</button></div><div class="generated-codes hidden" id="generatedCodes"><div class="generated-top"><div><strong>New codes</strong><small>These plaintext codes are shown only now. Save or deliver them before closing.</small></div><button class="license-copy" id="copyLicenses">Copy all</button></div><pre id="generatedList"></pre></div><div class="license-error" id="licenseError"></div><div class="license-stats" id="licenseStats"></div><div class="license-list" id="licenseList"><div class="license-empty">Loading…</div></div></div>`;document.body.appendChild(overlay);q('#licenseClose',overlay).onclick=()=>{overlay.remove();overlay=null};overlay.onclick=e=>{if(e.target===overlay){overlay.remove();overlay=null}};q('#generateLicenses',overlay).onclick=async()=>{const btn=q('#generateLicenses',overlay),count=Math.max(1,Math.min(100,Number(q('#licenseCount',overlay).value)||1)),source=q('#licenseSource',overlay).value.trim()||'manual';btn.disabled=true;showError('');const {data,error}=await window.__LANDLORD_SUPABASE__.rpc('admin_generate_license_codes',{p_count:count,p_source:source});btn.disabled=false;if(error){showError(error.message);return}const codes=(data||[]).map(x=>x.code);q('#generatedList',overlay).textContent=codes.join('\n');q('#generatedCodes',overlay).classList.remove('hidden');q('#copyLicenses',overlay).onclick=async()=>{await navigator.clipboard.writeText(codes.join('\n'));q('#copyLicenses',overlay).textContent='Copied ✓';setTimeout(()=>{if(q('#copyLicenses',overlay))q('#copyLicenses',overlay).textContent='Copy all'},1400)};await refresh()};await refresh()}
window.addEventListener('landlord:ready',mount);document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,500));setTimeout(mount,1200);
})();