(()=>{
const mq=matchMedia('(max-width:780px)');const isMobile=()=>mq.matches;let nav,bar,fab,sheet,search,quick,queued=false;
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const icons={home:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><path d="M3 10.5 12 3l9 7.5v9a1.5 1.5 0 0 1-1.5 1.5h-15A1.5 1.5 0 0 1 3 19.5z"/><path d="M9 21v-7h6v7"/></svg>',properties:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><rect x="3" y="3" width="8" height="8" rx="2"/><rect x="13" y="3" width="8" height="8" rx="2"/><rect x="3" y="13" width="8" height="8" rx="2"/><rect x="13" y="13" width="8" height="8" rx="2"/></svg>',rent:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><rect x="3" y="5" width="18" height="14" rx="3"/><path d="M7 9h10M7 13h6"/></svg>',money:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><path d="M4 19V9m5 10V5m5 14v-7m5 7V3"/></svg>',more:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/></svg>',search:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',user:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><circle cx="12" cy="8" r="4"/><path d="M4.5 21a7.5 7.5 0 0 1 15 0"/></svg>',plus:'<svg viewBox="0 0 24 24" fill="none" stroke-width="2"><path d="M12 5v14M5 12h14"/></svg>',building:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><path d="M4 21V5l8-3 8 3v16M8 8h2m4 0h2M8 12h2m4 0h2M8 16h2m4 0h2"/></svg>',person:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><circle cx="12" cy="8" r="3.5"/><path d="M5 21a7 7 0 0 1 14 0"/></svg>',tool:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><path d="M14 6a4 4 0 0 0-5 5L3 17l4 4 6-6a4 4 0 0 0 5-5l-3 3-3-3z"/></svg>',file:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><path d="M6 2h8l4 4v16H6z"/><path d="M14 2v5h5M9 12h6M9 16h6"/></svg>',bell:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg>',chart:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><path d="M4 20V10m6 10V4m6 16v-7m4 7H2"/></svg>',help:'<svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><circle cx="12" cy="12" r="9"/><path d="M9.8 9a2.5 2.5 0 1 1 3.4 2.3c-.8.4-1.2.8-1.2 1.7M12 17h.01"/></svg>'};
function nativeNav(page){q(`.navbtn[data-page="${page}"]`)?.click()}
function closeOverlays(){[sheet,search,quick].forEach(x=>x?.remove());sheet=search=quick=null}
function pageInfo(){const p=q('.navbtn.active')?.dataset.page||'home';const title=(q('#pageTitle')?.textContent||'Landlord OS').trim();return{p,title}}
function mountBar(){if(bar||!isMobile())return;bar=document.createElement('header');bar.className='mobile-appbar mobile-only';bar.innerHTML=`<div class="mobile-brandline"><div class="mobile-brandicon"><img src="./brand-icon.svg" alt=""></div><div class="mobile-titlewrap"><small>Landlord OS</small><h1 id="mobilePageTitle">Home</h1></div></div><div class="mobile-app-actions"><button class="mobile-icon-btn" id="appSearch" aria-label="Search">${icons.search}</button><button class="mobile-icon-btn mobile-avatar-btn" id="appAccount" aria-label="Account">${icons.user}</button></div>`;document.body.prepend(bar);q('#appSearch').onclick=openSearch;q('#appAccount').onclick=openMore;const sync=document.createElement('div');sync.className='mobile-syncbar mobile-only';sync.innerHTML='<i></i><span>Cloud synced · your portfolio is private</span>';bar.after(sync)}
function mountNav(){if(nav||!isMobile())return;nav=document.createElement('nav');nav.className='mobile-bottom-nav mobile-only';nav.innerHTML=`<button data-page="home">${icons.home}<b>Home</b></button><button data-page="properties">${icons.properties}<b>Properties</b></button><button data-page="rent">${icons.rent}<b>Rent</b></button><button data-page="expenses">${icons.money}<b>Money</b></button><button data-more>${icons.more}<b>More</b></button>`;document.body.appendChild(nav);qa('[data-page]',nav).forEach(b=>b.onclick=()=>nativeNav(b.dataset.page));q('[data-more]',nav).onclick=openMore}
function mountFab(){if(fab||!isMobile())return;fab=document.createElement('button');fab.className='mobile-fab mobile-only';fab.setAttribute('aria-label','Quick add');fab.innerHTML=icons.plus;document.body.appendChild(fab);fab.onclick=openQuick}
function quickButton(key,icon,label){return `<button data-q="${key}"><span>${icon}</span>${label}</button>`}
function openQuick(){closeOverlays();quick=document.createElement('div');quick.className='mobile-sheet-wrap mobile-only';quick.innerHTML=`<div class="mobile-sheet"><div class="sheet-handle"></div><div class="sheet-title"><div><small>Quick add</small><h2>What do you want to add?</h2></div><button data-close>×</button></div><div class="more-grid">${quickButton('property',icons.building,'Property')}${quickButton('tenant',icons.person,'Tenant')}${quickButton('payment',icons.rent,'Payment')}${quickButton('expense',icons.money,'Expense')}${quickButton('maintenance',icons.tool,'Maintenance')}</div></div>`;document.body.appendChild(quick);q('[data-close]',quick).onclick=closeOverlays;quick.onclick=e=>{if(e.target===quick)closeOverlays()};qa('[data-q]',quick).forEach(b=>b.onclick=()=>{const target=q(`[data-quick="${b.dataset.q}"]`);closeOverlays();setTimeout(()=>target?.click(),30)})}
function openMore(){closeOverlays();sheet=document.createElement('div');sheet.className='mobile-sheet-wrap mobile-only';sheet.innerHTML=`<div class="mobile-sheet"><div class="sheet-handle"></div><div class="sheet-title"><div><small>Workspace</small><h2>More</h2></div><button data-close>×</button></div><div class="more-grid"><button data-go="tenants"><span>${icons.person}</span>Tenants</button><button data-go="documents"><span>${icons.file}</span>Documents</button><button data-go="maintenance"><span>${icons.tool}</span>Maintenance</button><button data-go="reports"><span>${icons.chart}</span>Reports</button><button data-go="alerts"><span>${icons.bell}</span>Alerts</button><button id="mDocs"><span>${icons.help}</span>Documentation</button></div><div class="more-actions"><div id="mLang"></div><button id="mExport">Export backup</button><button id="mSignOut">Sign out</button></div></div>`;document.body.appendChild(sheet);q('[data-close]',sheet).onclick=closeOverlays;sheet.onclick=e=>{if(e.target===sheet)closeOverlays()};qa('[data-go]',sheet).forEach(b=>b.onclick=()=>{nativeNav(b.dataset.go);closeOverlays()});q('#mDocs').onclick=()=>{q('#documentationNav')?.click();closeOverlays()};const lc=q('#languageControl');if(lc){q('#mLang').appendChild(lc.cloneNode(true));const s=q('#mLang select');if(s)s.onchange=e=>{localStorage.setItem('landlord-os-language',e.target.value);location.reload()}}q('#mExport').onclick=()=>q('#exportBtn')?.click();q('#mSignOut').onclick=()=>q('#cloudSignOut')?.click()}
function openSearch(){closeOverlays();search=document.createElement('div');search.className='mobile-search-sheet mobile-only';search.innerHTML=`<div class="mobile-search-top"><button data-close aria-label="Back">←</button><input id="mSearchInput" placeholder="Search property or tenant"></div><div id="mSearchResults" class="mobile-search-results"><div class="mobile-search-hint">Search properties, addresses, tenants or email</div></div>`;document.body.appendChild(search);q('[data-close]',search).onclick=closeOverlays;const input=q('#mSearchInput'),out=q('#mSearchResults');setTimeout(()=>input.focus(),60);input.oninput=()=>{const d=q('#globalSearch');if(!d)return;d.value=input.value;d.dispatchEvent(new Event('input',{bubbles:true}));setTimeout(()=>{const src=q('#searchResults');out.innerHTML=src?.innerHTML||'<div class="mobile-search-hint">No matches</div>';qa('[data-hit]',out).forEach((b,i)=>b.onclick=()=>{q(`[data-hit="${i}"]`,src)?.click();closeOverlays()})},30)}}
function mountQuickActions(){if(!isMobile()||q('.mobile-quick-actions'))return;const cards=q('.cards6');if(!cards)return;const row=document.createElement('div');row.className='mobile-quick-actions mobile-only';row.innerHTML=`${quickButton('property',icons.building,'Property')}${quickButton('payment',icons.rent,'Payment')}${quickButton('expense',icons.money,'Expense')}${quickButton('maintenance',icons.tool,'Repair')}`;cards.before(row);qa('[data-q]',row).forEach(b=>b.onclick=()=>q(`[data-quick="${b.dataset.q}"]`)?.click())}
function polishHome(){if(!isMobile())return;const current=pageInfo().p;if(current!=='home')return;qa('.section-head').forEach(h=>{if((h.textContent||'').includes('Property performance')){const g=h.nextElementSibling;if(g?.classList.contains('property-grid'))qa('.property-card',g).forEach((c,i)=>c.style.display=i<3?'':'none')}})}
function updateState(){if(!isMobile())return;const {p,title}=pageInfo();const mt=q('#mobilePageTitle');if(mt)mt.textContent=title||'Home';qa('[data-page]',nav||document).forEach(b=>b.classList.toggle('active',b.dataset.page===p));q('[data-more]',nav||document)?.classList.toggle('active',!['home','properties','rent','expenses'].includes(p));mountQuickActions();polishHome();document.body.classList.add('mobile-app-ui')}
function enhance(){if(!isMobile()){closeOverlays();return}mountBar();mountNav();mountFab();updateState()}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhance()})}
new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true,characterData:true});mq.addEventListener?.('change',schedule);document.addEventListener('DOMContentLoaded',schedule);setTimeout(schedule,350);
})();