(()=>{
const isMobile=()=>matchMedia('(max-width:780px)').matches;
const labels={home:'Home',properties:'Properties',rent:'Rent',expenses:'Money'};
let mobileNav,moreSheet,searchSheet;
function q(sel,root=document){return root.querySelector(sel)}
function qa(sel,root=document){return [...root.querySelectorAll(sel)]}
function clickNav(label){const b=qa('.navbtn').find(x=>x.textContent.trim().startsWith(label));if(b)b.click()}
function mountNav(){if(!isMobile())return;if(!mobileNav){mobileNav=document.createElement('nav');mobileNav.className='mobile-bottom-nav mobile-only';mobileNav.innerHTML=`<button data-mob="home"><span>⌂</span><b>Home</b></button><button data-mob="properties"><span>▦</span><b>Properties</b></button><button data-mob="rent"><span>$</span><b>Rent</b></button><button data-mob="expenses"><span>◫</span><b>Money</b></button><button data-mob="more"><span>•••</span><b>More</b></button>`;document.body.appendChild(mobileNav);qa('[data-mob]',mobileNav).forEach(b=>b.onclick=()=>{if(b.dataset.mob==='more')openMore();else clickNav(labels[b.dataset.mob])})}}
function mountTopActions(){if(!isMobile())return;const top=q('.top');if(!top||q('.mobile-top-actions',top))return;const w=document.createElement('div');w.className='mobile-top-actions mobile-only';w.innerHTML='<button id="mobileSearch" aria-label="Search">⌕</button><button id="mobileMore" aria-label="More">•••</button>';top.appendChild(w);q('#mobileSearch').onclick=openSearch;q('#mobileMore').onclick=openMore}
function openMore(){if(moreSheet)moreSheet.remove();moreSheet=document.createElement('div');moreSheet.className='mobile-sheet-wrap mobile-only';moreSheet.innerHTML=`<div class="mobile-sheet"><div class="sheet-handle"></div><div class="sheet-title"><div><small>Landlord OS</small><h2>More</h2></div><button data-close>×</button></div><div class="more-grid"><button data-go="Tenants"><span>◎</span>Tenants</button><button data-go="Documents"><span>▤</span>Documents</button><button data-go="Maintenance"><span>⌁</span>Maintenance</button><button data-go="Reports"><span>▥</span>Reports</button><button data-go="Alerts"><span>!</span>Alerts</button><button id="moreDocs"><span>?</span>Documentation</button></div><div class="more-actions"><div id="mobileLanguageSlot"></div><button id="mobileExport">Export backup</button><button id="mobileSignOut">Sign out</button></div></div>`;document.body.appendChild(moreSheet);q('[data-close]',moreSheet).onclick=()=>moreSheet.remove();moreSheet.onclick=e=>{if(e.target===moreSheet)moreSheet.remove()};qa('[data-go]',moreSheet).forEach(b=>b.onclick=()=>{clickNav(b.dataset.go);moreSheet.remove()});q('#moreDocs').onclick=()=>{const d=q('#documentationNav');if(d)d.click();moreSheet.remove()};const lang=q('#languageControl');if(lang)q('#mobileLanguageSlot').appendChild(lang.cloneNode(true));const sel=q('#mobileLanguageSlot select');if(sel)sel.onchange=e=>{localStorage.setItem('landlord-os-language',e.target.value);location.reload()};q('#mobileExport').onclick=()=>q('#exportBtn')?.click();q('#mobileSignOut').onclick=()=>q('#cloudSignOut')?.click()}
function openSearch(){if(searchSheet)searchSheet.remove();searchSheet=document.createElement('div');searchSheet.className='mobile-search-sheet mobile-only';searchSheet.innerHTML=`<div class="mobile-search-top"><button data-close>←</button><input id="mobileGlobalSearch" placeholder="Search property or tenant" autofocus></div><div id="mobileSearchResults" class="mobile-search-results"><div class="mobile-search-hint">Search by property name, address, tenant or email</div></div>`;document.body.appendChild(searchSheet);q('[data-close]',searchSheet).onclick=()=>searchSheet.remove();const inp=q('#mobileGlobalSearch'),results=q('#mobileSearchResults');setTimeout(()=>inp.focus(),50);inp.oninput=()=>{const desktop=q('#globalSearch');if(!desktop)return;desktop.value=inp.value;desktop.dispatchEvent(new Event('input',{bubbles:true}));setTimeout(()=>{const dr=q('#searchResults');results.innerHTML=dr&&dr.innerHTML?dr.innerHTML:'<div class="mobile-search-hint">No matches</div>';qa('[data-hit]',results).forEach((b,i)=>b.onclick=()=>{q(`[data-hit="${i}"]`,dr)?.click();searchSheet.remove()})},20)}}
function compactHome(){if(!isMobile())return;const content=q('#content');if(!content)return;const secHeads=qa('.section-head',content);secHeads.forEach(h=>{const txt=h.textContent||'';if(txt.includes('Property performance')){const grid=h.nextElementSibling;if(grid?.classList.contains('property-grid'))qa('.property-card',grid).forEach((c,i)=>c.style.display=i<3?'':'none')}})}
function enhanceRent(){if(!isMobile())return;qa('.rent-row').forEach(r=>{if(r.dataset.mobileEnhanced)return;r.dataset.mobileEnhanced='1';r.classList.add('mobile-stack-row')})}
function syncActive(){if(!mobileNav)return;const active=q('.navbtn.active');const txt=active?.textContent.trim().toLowerCase()||'';qa('[data-mob]',mobileNav).forEach(b=>b.classList.remove('active'));let id='more';if(txt.startsWith('home'))id='home';else if(txt.startsWith('properties'))id='properties';else if(txt.startsWith('rent'))id='rent';else if(txt.startsWith('financial'))id='expenses';q(`[data-mob="${id}"]`,mobileNav)?.classList.add('active')}
function enhance(){if(!isMobile())return;mountNav();mountTopActions();compactHome();enhanceRent();syncActive();document.body.classList.add('mobile-redesign')}
new MutationObserver(()=>requestAnimationFrame(enhance)).observe(document.documentElement,{childList:true,subtree:true});addEventListener('resize',enhance);document.addEventListener('DOMContentLoaded',enhance);setTimeout(enhance,500);
})();