LOS.actions = {
  addProperty(data){ const p={id:LOS.uid('p'),name:String(data.name||'').trim(),address:String(data.address||'').trim(),rent:LOS.safeNumber(data.rent),image:String(data.image||'https://images.unsplash.com/photo-1600585152915-d208bec867a1?auto=format&fit=crop&w=1200&q=80')}; if(!p.name||!p.address||!p.rent) throw new Error('Property name, address and rent are required.'); LOS.state.properties.push(p); LOS.persist(); return p; },
  editProperty(id,data){ const p=LOS.property(id); if(!p) return; Object.assign(p,{name:String(data.name??p.name).trim(),address:String(data.address??p.address).trim(),rent:LOS.safeNumber(data.rent??p.rent),image:String(data.image??p.image)}); LOS.persist(); },
  addTenant(data){ const propertyId=String(data.propertyId||''); if(!LOS.property(propertyId)) throw new Error('Choose a valid property.'); if(LOS.tenantFor(propertyId)) throw new Error('This property already has a tenant.'); const t={id:LOS.uid('t'),propertyId,name:String(data.name||'').trim(),email:String(data.email||'').trim(),phone:String(data.phone||'').trim(),leaseStart:String(data.leaseStart||''),leaseEnd:String(data.leaseEnd||'')}; if(!t.name||!t.leaseStart||!t.leaseEnd) throw new Error('Tenant name and lease dates are required.'); if(new Date(t.leaseEnd)<new Date(t.leaseStart)) throw new Error('Lease end must be after lease start.'); LOS.state.tenants.push(t); LOS.persist(); return t; },
  editTenant(id,data){ const t=LOS.state.tenants.find(x=>x.id===id); if(!t) return; Object.assign(t,{name:String(data.name??t.name).trim(),email:String(data.email??t.email).trim(),phone:String(data.phone??t.phone).trim(),leaseStart:String(data.leaseStart??t.leaseStart),leaseEnd:String(data.leaseEnd??t.leaseEnd)}); LOS.persist(); },
  recordPayment(propertyId,amount,date){ const month=LOS.monthKey(new Date(`${date||new Date().toISOString().slice(0,10)}T12:00:00`)); const existing=LOS.paymentFor(propertyId,month); if(existing){ existing.amount=LOS.safeNumber(amount)||LOS.property(propertyId)?.rent||0; existing.date=date||new Date().toISOString().slice(0,10); } else { LOS.state.payments.push({id:LOS.uid('pay'),propertyId,month,amount:LOS.safeNumber(amount)||LOS.property(propertyId)?.rent||0,date:date||new Date().toISOString().slice(0,10)}); } LOS.persist(); },
  addExpense(data){ const e={id:LOS.uid('e'),propertyId:String(data.propertyId||''),category:String(data.category||'Other').trim(),amount:LOS.safeNumber(data.amount),date:String(data.date||new Date().toISOString().slice(0,10)),note:String(data.note||'').trim()}; if(!LOS.property(e.propertyId)||!e.amount) throw new Error('Property and amount are required.'); LOS.state.expenses.push(e); LOS.persist(); return e; },
  deleteExpense(id){ LOS.state.expenses=LOS.state.expenses.filter(e=>e.id!==id); LOS.persist(); },
  dismissAlert(id){ if(!LOS.state.dismissedAlerts.includes(id)) LOS.state.dismissedAlerts.push(id); LOS.persist(); },
  exportData(){ LOS.download(`landlord-os-${new Date().toISOString().slice(0,10)}.json`,LOS.state); },
  resetDemo(){ localStorage.removeItem(LOS.KEY); LOS.state=LOS.clone(LOS.seed); LOS.persist(); }
};
